# -*- coding: utf-8 -*-
"""扫描事件 Script(code=355) 指令，生成 MV 防崩插件 MonlineShim.js。

作用:
  1) 覆写 Game_Interpreter.command355，用 try/catch 包住 eval —— 任何未定义
     脚本/报错都被吞掉，事件继续执行，游戏不再因 Ruby 脚本而卡死/崩溃。
  2) 为脚本里引用的自定义 Scene / 全局函数 / 全局对象 / $game_* 原型方法
     自动生成空实现(no-op)桩，减少报错噪声。
"""
import json
import os
import glob
import re

D = "Monline-MV/data"
OUT_JS = "Monline-MV/js/plugins/MonlineShim.js"

JS_BUILTIN = set("""Math JSON Object Array String Number Boolean Date RegExp Error
parseInt parseFloat isNaN isFinite eval decodeURIComponent encodeURIComponent
console window document alert confirm prompt setTimeout setInterval
clearTimeout clearInterval String Number $dataSystem""".split())

KNOWN_GLOBAL = set("""SceneManager DataManager AudioManager ImageManager Input
StorageManager ConfigManager TextManager ColorManager BattleManager Utils JsonEx
Game_Interpreter Game_Map Game_Party Game_Troop Game_System Game_Switches
Game_Variables Game_SelfSwitches Game_Timer Game_Screen Game_Picture Game_Player
Game_Followers Game_Actors Game_Actor Game_Enemy Game_Battler Game_Message
Game_CommonEvent Game_Temp Game_Item Game_Action Game_ActionResult
Sprite Window Bitmap Tone Color Rectangle Point SoundEffect ResourceHandler
Scene_Base Scene_Boot Scene_Title Scene_Map Scene_Menu Scene_Item Scene_Skill
Scene_Equip Scene_Status Scene_Options Scene_Save Scene_Load Scene_GameEnd
Scene_Battle Scene_Debug Scene_File Scene_ItemBase Scene_Name Scene_Shop
Scene_Message EventEmitter""".split())

# $game_x -> 对应的 MV 原型类(在这些类上补方法桩)
DOLLAR_CLASS = {
    "game_actors": ["Game_Actors", "Game_Actor"],
    "game_party": ["Game_Party"],
    "game_player": ["Game_Player"],
    "game_map": ["Game_Map"],
    "game_system": ["Game_System"],
    "game_switches": ["Game_Switches"],
    "game_variables": ["Game_Variables"],
    "game_self_switches": ["Game_SelfSwitches"],
    "game_screen": ["Game_Screen"],
    "game_timer": ["Game_Timer"],
    "game_troop": ["Game_Troop"],
    "game_message": ["Game_Message"],
    "game_temp": ["Game_Temp"],
}


def collect_scripts():
    scripts = []
    for f in glob.glob(os.path.join(D, "Map*.json")):
        if os.path.basename(f) == "MapInfos.json":
            continue
        m = json.load(open(f, encoding='utf-8'))
        for ev in (m.get('events') or []):
            if not isinstance(ev, dict):
                continue
            for pg in (ev.get('pages') or []):
                if not isinstance(pg, dict):
                    continue
                for c in (pg.get('list') or []):
                    if isinstance(c, dict) and c.get('code') == 355:
                        p = c.get('parameters') or []
                        if p:
                            scripts.append(str(p[0]))
    ce = json.load(open(os.path.join(D, "CommonEvents.json"), encoding='utf-8'))
    for e in ce:
        if isinstance(e, dict):
            for c in (e.get('list') or []):
                if isinstance(c, dict) and c.get('code') == 355:
                    p = c.get('parameters') or []
                    if p:
                        scripts.append(str(p[0]))
    return scripts


def extract(text):
    scenes = set(re.findall(r'\b(Scene_[A-Za-z0-9_]+)\b', text))
    scenes = {s for s in scenes if s not in KNOWN_GLOBAL}

    funcs = set()
    for mm in re.finditer(r'(?<![\w.$])([a-zA-Z_]\w*)\s*\(', text):
        nm = mm.group(1)
        if nm in JS_BUILTIN or nm in KNOWN_GLOBAL:
            continue
        funcs.add(nm)

    objs = {}
    for mm in re.finditer(r'(?<![\w.$])([a-zA-Z_]\w*)\.([a-zA-Z_]\w*)\s*\(', text):
        o, meth = mm.group(1), mm.group(2)
        if o in JS_BUILTIN or o in KNOWN_GLOBAL or o.startswith('$'):
            continue
        objs.setdefault(o, set()).add(meth)

    proto = {}
    for mm in re.finditer(r'\$(game_[a-zA-Z_]+)(?:\[\d+\])?\.([a-zA-Z_]\w*)\s*\(', text):
        cls, meth = mm.group(1), mm.group(2)
        proto.setdefault(cls, set()).add(meth)

    return scenes, funcs, objs, proto


def gen_js(scenes, funcs, objs, proto, n_scripts):
    L = []
    L.append("//=============================================================================")
    L.append("// MonlineShim.js  (auto-generated by gen_shim.py)")
    L.append("// VX Ace -> MV port: prevents crashes from 'Script'(code 355) event commands.")
    L.append("//=============================================================================")
    L.append("/*:")
    L.append(" * @plugindesc VX Ace script-command safety shim (prevents crashes).")
    L.append(" * @author Monline port")
    L.append(" *")
    L.append(" * @help")
    L.append(" * Wraps Game_Interpreter.command355 in try/catch so undefined VX Ace")
    L.append(" * scripts no longer halt the game, and defines no-op stubs for custom")
    L.append(" * globals/functions/scenes/prototype-methods referenced by events.")
    L.append(" *")
    L.append(" * Stubbed: %d scenes, %d functions, %d objects, %d $game_* classes"
             % (len(scenes), len(funcs), len(objs), len(proto)))
    L.append(" */")
    L.append("(function() {")
    L.append("    'use strict';")
    L.append("")
    L.append("    var MonlineShim = { scenes: [], functions: [], objects: {}, methods: {} };")
    L.append("    window.MonlineShim = MonlineShim;")
    L.append("")
    L.append("    // --- 1) make code-355 script commands non-fatal ---")
    L.append("    Game_Interpreter.prototype.command355 = function() {")
    L.append("        var script = this.currentCommand().parameters[0] + '\\n';")
    L.append("        while (this.nextEventCode() === 655) {")
    L.append("            this._index++;")
    L.append("            script += this.currentCommand().parameters[0] + '\\n';")
    L.append("        }")
    L.append("        try {")
    L.append("            eval(script);")
    L.append("        } catch (e) {")
    L.append("            console.warn('MonlineShim: ignored script error: ' + (e && e.message));")
    L.append("        }")
    L.append("        this._index++;")
    L.append("        return true;")
    L.append("    };")
    L.append("")
    L.append("    // --- 2) stub custom Scene classes ---")
    L.append("    function makeScene(name) {")
    L.append("        var S = function() { this.initialize.apply(this, arguments); };")
    L.append("        S.prototype = Object.create(Scene_Base.prototype);")
    L.append("        S.prototype.constructor = S;")
    L.append("        S.prototype.initialize = function() { Scene_Base.prototype.initialize.call(this); };")
    L.append("        S.prototype.create = function() { Scene_Base.prototype.create.call(this); };")
    L.append("        S.prototype.start = function() { Scene_Base.prototype.start.call(this); };")
    L.append("        return S;")
    L.append("    }")
    for s in sorted(scenes):
        L.append("    if (typeof window.%s === 'undefined') { window.%s = makeScene('%s'); MonlineShim.scenes.push('%s'); }"
                 % (s, s, s, s))
    L.append("")
    L.append("    // --- 3) stub custom global functions ---")
    for f in sorted(funcs):
        L.append("    if (typeof window.%s === 'undefined') { window.%s = function() {}; MonlineShim.functions.push('%s'); }"
                 % (f, f, f))
    L.append("")
    L.append("    // --- 4) stub custom global objects (with their methods) ---")
    for o in sorted(objs):
        # 该名字也可能同时是函数(section 3)，故用属性挂载而非重建
        L.append("    if (typeof window.%s === 'undefined') { window.%s = {}; }" % (o, o))
        for m in sorted(objs[o]):
            L.append("    if (!window.%s.%s) { window.%s.%s = function(){}; }" % (o, m, o, m))
        L.append("    MonlineShim.objects['%s'] = %d;" % (o, len(objs[o])))
    L.append("")
    L.append("    // --- 5) stub custom $game_* prototype methods ---")
    for cls in sorted(proto):
        tgt = DOLLAR_CLASS.get(cls, [])
        for m in sorted(proto[cls]):
            for c in tgt:
                L.append("    if (typeof %s !== 'undefined' && !%s.prototype.%s) { %s.prototype.%s = function() {}; MonlineShim.methods['%s.%s']=1; }"
                         % (c, c, m, c, m, c, m))
    L.append("})();")
    L.append("")
    return "\n".join(L)


def main():
    scripts = collect_scripts()
    text = "\n".join(scripts)
    scenes, funcs, objs, proto = extract(text)
    js = gen_js(scenes, funcs, objs, proto, len(scripts))
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    open(OUT_JS, 'w', encoding='utf-8').write(js)
    print("scripts scanned:", len(scripts))
    print("stubbed scenes=%d funcs=%d objects=%d game-classes=%d"
          % (len(scenes), len(funcs), len(objs), len(proto)))
    print("scenes:", sorted(scenes)[:20])
    print("funcs sample:", sorted(funcs)[:25])
    print("objects:", {k: sorted(v)[:4] for k, v in list(objs.items())[:12]})


if __name__ == "__main__":
    main()
