# -*- coding: utf-8 -*-
"""Generate js/plugins/MonlineImageExt.js.

The problem
-----------
``ImageManager.loadBitmap`` (rpg_managers.js:859) hard-codes the extension:

    var path = folder + encodeURIComponent(filename) + '.png';

But this game's art is mostly JPEG - the ported ``img/pictures`` folder holds
3 287 ``.jpg``, 1 318 ``.png`` and 2 ``.jpeg`` files.  Of the 4 421 distinct
pictures the events actually ask for, **3 144 resolve only as .jpg/.jpeg**, so
without a fallback roughly 71% of every CG / scene image in the game silently
renders blank (the AssetGuard turns the failed load into an empty bitmap).

The fix
-------
Same approach already used for audio (``MonlineAudioExt.js``): ship a manifest
of the files that are *not* png and let a small plugin pick the right extension
before MV builds the URL.  The manifest keeps the number of 404s at zero, which
also keeps the missing-asset diagnostics meaningful.

Usage:
    python gen_image_ext.py            # scan ./Monline-MV/img, write the plugin
    python gen_image_ext.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_PROJECTS = [os.path.join(HERE, "Monline-MV"),
                    os.path.join(HERE, "mv_project")]

# MV will only ever ask for an <img> here; skip the stray .txt files that
# shipped alongside the tilesets.
IMAGE_EXTS = {".jpg", ".jpeg", ".jpe", ".bmp", ".gif", ".webp"}

PLUGIN_TEMPLATE = """// Generated by gen_image_ext.py -- do not edit by hand.
// VX Ace -> MV port: the art is mostly JPEG, but ImageManager requests .png.
// Picks the real extension before the URL is built (%d non-png asset(s)).
(function() {
    'use strict';
    var EXT = %s;

    var _loadBitmap = ImageManager.loadBitmap;
    ImageManager.loadBitmap = function(folder, filename, hue, smooth) {
        if (filename) {
            var ext = EXT[folder + filename];
            if (ext) {
                // Mirror the engine exactly (rpg_managers.js:859) with the
                // extension swapped in.
                var path = folder + encodeURIComponent(filename) + ext;
                var bitmap = this.loadNormalBitmap(path, hue || 0);
                bitmap.smooth = smooth;
                return bitmap;
            }
        }
        return _loadBitmap.apply(this, arguments);
    };
})();
"""


def build_manifest(img_root):
    """{ "img/pictures/Echidna1": ".jpg", ... } for every non-png image."""
    manifest = {}
    for dirpath, _dirnames, filenames in os.walk(img_root):
        for fn in filenames:
            ext = os.path.splitext(fn)[1].lower()
            if ext not in IMAGE_EXTS:
                continue
            stem = os.path.splitext(fn)[0]
            # key must match `folder + filename` used by ImageManager
            rel = os.path.relpath(os.path.join(dirpath, stem), os.path.dirname(img_root))
            key = rel.replace(os.sep, "/")
            manifest[key] = ext
    return manifest


def run(project, dry):
    img_root = os.path.join(project, "img")
    plugin_dir = os.path.join(project, "js", "plugins")
    if not os.path.isdir(img_root):
        print("  [skip] no img/ in %s" % project)
        return
    manifest = build_manifest(img_root)
    out = os.path.join(plugin_dir, "MonlineImageExt.js")
    print("  %-46s %d entries" % (os.path.basename(project), len(manifest)))
    if dry:
        return
    os.makedirs(plugin_dir, exist_ok=True)
    # compact, sorted, stable output
    body = "{\n" + ",\n".join(
        '        %s: %s' % (json.dumps(k, ensure_ascii=False), json.dumps(v))
        for k, v in sorted(manifest.items())
    ) + "\n    }"
    with open(out, "w", encoding="utf-8") as f:
        f.write(PLUGIN_TEMPLATE % (len(manifest), body))

    # register in plugins.js (skip if already present)
    pj = os.path.join(project, "js", "plugins.js")
    with open(pj, encoding="utf-8") as f:
        txt = f.read()
    if "MonlineImageExt" in txt:
        print("  plugins.js: already registered")
        return
    entry = ('{"name": "MonlineImageExt", "status": true, '
             '"description": "Real file extension for ported images that are not .png.", '
             '"parameters": {}},\n')
    marker = '{"name": "MonlineAudioExt"'
    if marker in txt:
        txt = txt.replace(marker, entry + marker, 1)
    else:
        txt = txt.replace("[\n", "[\n" + entry, 1)
    with open(pj, "w", encoding="utf-8") as f:
        f.write(txt)
    print("  plugins.js: registered MonlineImageExt")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--project", action="append")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    for p in (args.project or DEFAULT_PROJECTS):
        p = os.path.abspath(p)
        print(p)
        run(p, args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
