"""Register one or more plugin entries in js/plugins.js of both project copies.

Usage:
    python _shots/add_plugin.py MonlineFoo "description" [MonlineBar "desc2" ...]

Entries are appended (in order) if not already present, then both
Monline-MV/js/plugins.js and mv_project/js/plugins.js are rewritten in RPG
Maker's own one-entry-per-line form so the copies stay byte-identical.
"""
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'Monline-MV', 'js', 'plugins.js')
DST = os.path.join(ROOT, 'mv_project', 'js', 'plugins.js')

HDR = ('// Generated by RPG Maker.\n'
       '// Do not edit this file directly.\n'
       'var $plugins =\n[\n')


def load(path):
    s = io.open(path, encoding='utf-8').read()
    entries, _ = json.JSONDecoder().raw_decode(s[s.index('['):])
    return entries


def dump(entries):
    text = HDR
    for i, e in enumerate(entries):
        text += json.dumps(e, ensure_ascii=False, separators=(',', ':'))
        text += '' if i == len(entries) - 1 else ',\n'
    text += '\n];\n'
    return text


def main(argv):
    if len(argv) < 2 or len(argv) % 2:
        print(__doc__)
        return 1
    entries = load(SRC)
    names = [e['name'] for e in entries]
    for i in range(0, len(argv), 2):
        name, desc = argv[i], argv[i + 1]
        if name in names:
            print('already registered:', name)
            continue
        entries.append({'name': name, 'status': True,
                        'description': desc, 'parameters': {}})
        names.append(name)
        print('registered:', name)
    text = dump(entries)
    io.open(SRC, 'w', encoding='utf-8', newline='\n').write(text)
    io.open(DST, 'w', encoding='utf-8', newline='\n').write(text)
    print('plugins:', len(entries))
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
