"""Keep Monline-MV/js/plugins.js and mv_project/js/plugins.js identical.

Both project copies must load the same plugin list in the same order.
The file is re-serialised in RPG Maker's own compact one-entry-per-line form
so the two copies are byte-identical and `node --check` clean.
"""
import io, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'Monline-MV', 'js', 'plugins.js')
DST = os.path.join(ROOT, 'mv_project', 'js', 'plugins.js')


def load(path):
    s = io.open(path, encoding='utf-8').read()
    # raw_decode stops at the end of the FIRST complete JSON value, so a stray
    # trailing `];` cannot make this blow up the way `rindex(']')` does.
    entries, _ = json.JSONDecoder().raw_decode(s[s.index('['):])
    return entries


def dump(entries):
    text = ('// Generated by RPG Maker.\n'
            '// Do not edit this file directly.\n'
            'var $plugins =\n[\n')
    for i, e in enumerate(entries):
        text += json.dumps(e, ensure_ascii=False, separators=(',', ':'))
        text += '' if i == len(entries) - 1 else ',\n'
    text += '\n];\n'
    return text


def main():
    entries = load(SRC)
    names = [e['name'] for e in entries]
    dup = [n for n in set(names) if names.count(n) > 1]
    if dup:
        print('DUPLICATE plugin entries:', dup, file=sys.stderr)
        return 1
    text = dump(entries)
    io.open(SRC, 'w', encoding='utf-8').write(text)
    io.open(DST, 'w', encoding='utf-8').write(text)
    print('plugins synced:', len(entries))
    for n in names:
        print('   ', n)
    return 0


if __name__ == '__main__':
    sys.exit(main())
