// Generated by port_assets.py -- do not edit by hand.
// Tells AudioManager the real extension of files that are not .ogg.
(function() {
    var EXT = {
        "bgm/Espionage LOOP MOVING": ".wav",
        "bgm/Event - Danger": ".wav",
        "bgm/Exploration - Church": ".wav",
        "bgm/Exploration - Desert Underground": ".mp3",
        "bgm/Exploration - Dungeon": ".wav",
        "bgm/Exploration - Forest": ".wav",
        "bgm/Exploration - Mirane": ".wav",
        "bgm/Exploration - Mystic Woods": ".wav",
        "bgm/Exploration - Mythic Cliffs": ".wav",
        "bgm/Exploration - Pyramid": ".mp3",
        "bgm/Festival": ".wav",
        "bgm/Hula Dance": ".mp3",
        "bgm/Intro Theme": ".wav",
        "bgm/Medieval Market LOOP": ".wav",
        "bgm/Raving Energy": ".mp3",
        "bgm/Robin's Theme": ".wav",
        "bgm/Title Theme": ".wav",
        "bgm/Vessel of the Sea Goddess": ".wav",
        "bgm/Village": ".wav",
        "bgs/AMBIENCE_Forest_Wind_Stream_10sec_loop_stereo": ".wav",
        "bgs/CAR_ENGINE_i6_3L_5500_RPM_loop_mono": ".wav",
        "bgs/WATER_Sea_Waves_Small_15sec_loop_stereo": ".wav",
        "bgs/Whispering LOOP": ".wav",
        "me/Dramatic Defeat": ".wav",
        "me/Harp C": ".wav",
        "me/Harp D": ".wav",
        "me/Harp E": ".wav",
        "me/Harp F": ".wav",
        "me/Harp G": ".wav",
        "se/CAR_Start_Engine_Mixed_stereo": ".wav",
        "se/Chopping": ".wav",
        "se/Koto Twang": ".wav",
        "se/Owl Hoot Effect": ".mp3",
        "se/Page Turn": ".wav",
        "se/Police-siren-loop": ".mp3",
        "se/Spray": ".wav",
        "se/Whoosh 1": ".wav",
    };
    var _createBuffer = AudioManager.createBuffer;
    AudioManager.createBuffer = function(folder, name) {
        var ext = EXT[folder + '/' + name];
        if (ext) {
            var url = this._path + folder + '/' + encodeURIComponent(name) + ext;
            return new WebAudio(url);
        }
        return _createBuffer.call(this, folder, name);
    };
})();
