//=============================================================================
// MonlineShim.js  (auto-generated by gen_shim.py)
// VX Ace -> MV port: prevents crashes from 'Script'(code 355) event commands.
//=============================================================================
/*:
 * @plugindesc VX Ace script-command safety shim (prevents crashes).
 * @author Monline port
 *
 * @help
 * Wraps Game_Interpreter.command355 in try/catch so undefined VX Ace
 * scripts no longer halt the game, and defines no-op stubs for custom
 * globals/functions/scenes/prototype-methods referenced by events.
 *
 * Stubbed: 3 scenes, 35 functions, 4 objects, 3 $game_* classes
 */
(function() {
    'use strict';

    var MonlineShim = { scenes: [], functions: [], objects: {}, methods: {} };
    window.MonlineShim = MonlineShim;

    // --- 1) make code-355 script commands non-fatal ---
    // Fallback only: MonlineRubyBridge (loaded after this) replaces this with
    // a full Ruby->JS translation.  Kept as-is so the port still boots if the
    // bridge is ever disabled.
    // `this._index` is deliberately NOT advanced here: MV's executeCommand()
    // already increments it after the command returns true.
    Game_Interpreter.prototype.command355 = function() {
        var script = this.currentCommand().parameters[0] + '\n';
        while (this.nextEventCode() === 655) {
            this._index++;
            script += this.currentCommand().parameters[0] + '\n';
        }
        try {
            eval(script);
        } catch (e) {
            console.warn('MonlineShim: ignored script error: ' + (e && e.message));
        }
        return true;
    };

    // --- 2) stub custom Scene classes ---
    // These scenes were never ported, so the stand-in shows a short notice.
    // It must still be exitable - otherwise entering one silently soft-locks
    // the game, which is indistinguishable from the crash this port is fixing.
    function makeScene(name) {
        var S = function() { this.initialize.apply(this, arguments); };
        S.prototype = Object.create(Scene_Base.prototype);
        S.prototype.constructor = S;
        S.prototype.initialize = function() { Scene_Base.prototype.initialize.call(this); };
        S.prototype.create = function() {
            Scene_Base.prototype.create.call(this);
            // A visible notice beats a blank screen: the player can tell this is
            // a missing feature rather than a hang.
            try {
                var help = new Window_Help(2);
                help.setText('This scene has not been ported yet:\n' + name +
                             '\nPress OK or Cancel to go back.');
                help.y = Graphics.boxHeight - help.height;
                this.addWindow(help);
            } catch (e) { /* Window_Help unavailable - still exitable */ }
        };
        S.prototype.start = function() { Scene_Base.prototype.start.call(this); };
        S.prototype.update = function() {
            Scene_Base.prototype.update.call(this);
            if (Input.isTriggered('ok') || Input.isTriggered('cancel')) {
                SceneManager.goto(Scene_Map);
            }
        };
        try { Object.defineProperty(S, 'name', { value: name, configurable: true }); }
        catch (e) { /* Function#name is read-only on this engine - harmless */ }
        return S;
    }
    if (typeof window.Scene_Crafting === 'undefined') { window.Scene_Crafting = makeScene('Scene_Crafting'); MonlineShim.scenes.push('Scene_Crafting'); }
    if (typeof window.Scene_LearnSkill === 'undefined') { window.Scene_LearnSkill = makeScene('Scene_LearnSkill'); MonlineShim.scenes.push('Scene_LearnSkill'); }
    if (typeof window.Scene_PXEBestChoose === 'undefined') { window.Scene_PXEBestChoose = makeScene('Scene_PXEBestChoose'); MonlineShim.scenes.push('Scene_PXEBestChoose'); }

    // --- 3) stub custom global functions ---
    if (typeof window.Clear_Coord === 'undefined') { window.Clear_Coord = function() {}; MonlineShim.functions.push('Clear_Coord'); }
    if (typeof window.Set_Coord === 'undefined') { window.Set_Coord = function() {}; MonlineShim.functions.push('Set_Coord'); }
    if (typeof window.anchor_picture_to_event === 'undefined') { window.anchor_picture_to_event = function() {}; MonlineShim.functions.push('anchor_picture_to_event'); }
    if (typeof window.anchor_picture_to_map === 'undefined') { window.anchor_picture_to_map = function() {}; MonlineShim.functions.push('anchor_picture_to_map'); }
    if (typeof window.anchor_picture_to_player === 'undefined') { window.anchor_picture_to_player = function() {}; MonlineShim.functions.push('anchor_picture_to_player'); }
    if (typeof window.anchor_picture_to_screen === 'undefined') { window.anchor_picture_to_screen = function() {}; MonlineShim.functions.push('anchor_picture_to_screen'); }
    if (typeof window.cam_center === 'undefined') { window.cam_center = function() {}; MonlineShim.functions.push('cam_center'); }
    if (typeof window.cam_follow === 'undefined') { window.cam_follow = function() {}; MonlineShim.functions.push('cam_follow'); }
    if (typeof window.cam_set === 'undefined') { window.cam_set = function() {}; MonlineShim.functions.push('cam_set'); }
    if (typeof window.chain_commands === 'undefined') { window.chain_commands = function() {}; MonlineShim.functions.push('chain_commands'); }
    if (typeof window.char_effects === 'undefined') { window.char_effects = function() {}; MonlineShim.functions.push('char_effects'); }
    if (typeof window.disable_choice === 'undefined') { window.disable_choice = function() {}; MonlineShim.functions.push('disable_choice'); }
    if (typeof window.disable_good === 'undefined') { window.disable_good = function() {}; MonlineShim.functions.push('disable_good'); }
    if (typeof window.equip_armor_by_etype === 'undefined') { window.equip_armor_by_etype = function() {}; MonlineShim.functions.push('equip_armor_by_etype'); }
    if (typeof window.fade_fog === 'undefined') { window.fade_fog = function() {}; MonlineShim.functions.push('fade_fog'); }
    if (typeof window.gain_armor === 'undefined') { window.gain_armor = function() {}; MonlineShim.functions.push('gain_armor'); }
    if (typeof window.get_hp_percent === 'undefined') { window.get_hp_percent = function() {}; MonlineShim.functions.push('get_hp_percent'); }
    if (typeof window.get_shop === 'undefined') { window.get_shop = function() {}; MonlineShim.functions.push('get_shop'); }
    if (typeof window.hide_choice === 'undefined') { window.hide_choice = function() {}; MonlineShim.functions.push('hide_choice'); }
    if (typeof window.hide_good === 'undefined') { window.hide_good = function() {}; MonlineShim.functions.push('hide_good'); }
    if (typeof window.light === 'undefined') { window.light = function() {}; MonlineShim.functions.push('light'); }
    if (typeof window.nel_textpop === 'undefined') { window.nel_textpop = function() {}; MonlineShim.functions.push('nel_textpop'); }
    if (typeof window.price_good === 'undefined') { window.price_good = function() {}; MonlineShim.functions.push('price_good'); }
    if (typeof window.reflect_sprite === 'undefined') { window.reflect_sprite = function() {}; MonlineShim.functions.push('reflect_sprite'); }
    if (typeof window.remove_bar === 'undefined') { window.remove_bar = function() {}; MonlineShim.functions.push('remove_bar'); }
    if (typeof window.remove_equip === 'undefined') { window.remove_equip = function() {}; MonlineShim.functions.push('remove_equip'); }
    if (typeof window.setAllSelf === 'undefined') { window.setAllSelf = function() {}; MonlineShim.functions.push('setAllSelf'); }
    if (typeof window.setSelfSwitch === 'undefined') { window.setSelfSwitch = function() {}; MonlineShim.functions.push('setSelfSwitch'); }
    if (typeof window.set_symbols === 'undefined') { window.set_symbols = function() {}; MonlineShim.functions.push('set_symbols'); }
    if (typeof window.show_fog === 'undefined') { window.show_fog = function() {}; MonlineShim.functions.push('show_fog'); }
    if (typeof window.snooze_bar === 'undefined') { window.snooze_bar = function() {}; MonlineShim.functions.push('snooze_bar'); }
    if (typeof window.tint_fog === 'undefined') { window.tint_fog = function() {}; MonlineShim.functions.push('tint_fog'); }
    if (typeof window.weather === 'undefined') { window.weather = function() {}; MonlineShim.functions.push('weather'); }
    if (typeof window.zoom_event_sprite === 'undefined') { window.zoom_event_sprite = function() {}; MonlineShim.functions.push('zoom_event_sprite'); }
    if (typeof window.zoom_player_sprite === 'undefined') { window.zoom_player_sprite = function() {}; MonlineShim.functions.push('zoom_player_sprite'); }

    // --- 4) stub custom global objects (with their methods) ---
    if (typeof window.MashQTE === 'undefined') { window.MashQTE = {}; }
    if (!window.MashQTE.play) { window.MashQTE.play = function(){}; }
    MonlineShim.objects['MashQTE'] = 1;
    if (typeof window.TargetQTE === 'undefined') { window.TargetQTE = {}; }
    if (!window.TargetQTE.play) { window.TargetQTE.play = function(){}; }
    MonlineShim.objects['TargetQTE'] = 1;
    if (typeof window.light === 'undefined') { window.light = {}; }
    if (!window.light.setup) { window.light.setup = function(){}; }
    MonlineShim.objects['light'] = 1;
    if (typeof window.map_effects === 'undefined') { window.map_effects = {}; }
    if (!window.map_effects.set_color) { window.map_effects.set_color = function(){}; }
    if (!window.map_effects.set_gaussian_blur) { window.map_effects.set_gaussian_blur = function(){}; }
    if (!window.map_effects.set_hue) { window.map_effects.set_hue = function(){}; }
    if (!window.map_effects.set_linear_blur) { window.map_effects.set_linear_blur = function(){}; }
    if (!window.map_effects.set_opacity) { window.map_effects.set_opacity = function(){}; }
    if (!window.map_effects.set_pixelize) { window.map_effects.set_pixelize = function(){}; }
    if (!window.map_effects.set_radial_blur) { window.map_effects.set_radial_blur = function(){}; }
    if (!window.map_effects.set_tone) { window.map_effects.set_tone = function(){}; }
    if (!window.map_effects.set_wave) { window.map_effects.set_wave = function(){}; }
    if (!window.map_effects.set_zoom) { window.map_effects.set_zoom = function(){}; }
    if (!window.map_effects.set_zoom_blur) { window.map_effects.set_zoom_blur = function(){}; }
    if (!window.map_effects.setup_blur) { window.map_effects.setup_blur = function(){}; }
    MonlineShim.objects['map_effects'] = 12;

    // --- 5) stub custom $game_* prototype methods ---
    if (typeof Game_Actors !== 'undefined' && !Game_Actors.prototype.gain_jp) { Game_Actors.prototype.gain_jp = function() {}; MonlineShim.methods['Game_Actors.gain_jp']=1; }
    if (typeof Game_Actor !== 'undefined' && !Game_Actor.prototype.gain_jp) { Game_Actor.prototype.gain_jp = function() {}; MonlineShim.methods['Game_Actor.gain_jp']=1; }
    if (typeof Game_Party !== 'undefined' && !Game_Party.prototype.change_inventory) { Game_Party.prototype.change_inventory = function() {}; MonlineShim.methods['Game_Party.change_inventory']=1; }
    if (typeof Game_Party !== 'undefined' && !Game_Party.prototype.item_number) { Game_Party.prototype.item_number = function() {}; MonlineShim.methods['Game_Party.item_number']=1; }
    if (typeof Game_Party !== 'undefined' && !Game_Party.prototype.merge_inventories) { Game_Party.prototype.merge_inventories = function() {}; MonlineShim.methods['Game_Party.merge_inventories']=1; }
    if (typeof Game_Party !== 'undefined' && !Game_Party.prototype.swap_order) { Game_Party.prototype.swap_order = function() {}; MonlineShim.methods['Game_Party.swap_order']=1; }
    if (typeof Game_Player !== 'undefined' && !Game_Player.prototype.flash) { Game_Player.prototype.flash = function() {}; MonlineShim.methods['Game_Player.flash']=1; }
    if (typeof Game_Player !== 'undefined' && !Game_Player.prototype.shake) { Game_Player.prototype.shake = function() {}; MonlineShim.methods['Game_Player.shake']=1; }
})();
